<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">mapDateToIsoDate</value>
  <value name="encodeutf8">true</value>
  <value name="body">T2JqZWN0CWRhdGUgPSBudWxsOw0KDQovLyBwaXBlbGluZQ0KSURhdGFDdXJzb3IgcGlwZWxpbmVD
dXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNCmJvb2xlYW4gZXhpc3RzID0gcGlwZWxpbmVD
dXJzb3IuZmlyc3QoImRhdGUiKTsNCmlmIChleGlzdHMpIGRhdGUgPSBwaXBlbGluZUN1cnNvci5n
ZXRWYWx1ZSgpOw0KcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOw0KDQppZiAoIWV4aXN0cykgcmV0
dXJuOw0KDQpTdHJpbmcgbm93QXNJU08gPSBudWxsOw0KaWYobnVsbCAhPSBkYXRlKXsNCmphdmEu
dXRpbC5UaW1lWm9uZSB0eiA9IGphdmEudXRpbC5UaW1lWm9uZS5nZXRUaW1lWm9uZSgiVVRDIik7
DQpqYXZhLnRleHQuRGF0ZUZvcm1hdCBkZiA9IG5ldyBqYXZhLnRleHQuU2ltcGxlRGF0ZUZvcm1h
dCgieXl5eS1NTS1kZCdaJyIpOyAvLyBRdW90ZWQgIloiIHRvIGluZGljYXRlIFVUQywgbm8gdGlt
ZXpvbmUgb2Zmc2V0DQpkZi5zZXRUaW1lWm9uZSh0eik7DQpub3dBc0lTTyA9IGRmLmZvcm1hdCgo
amF2YS51dGlsLkRhdGUpZGF0ZSk7DQp9DQoNCi8vIHBpcGVsaW5lDQpJRGF0YUN1cnNvciBwaXBl
bGluZUN1cnNvcl8xID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQpJRGF0YVV0aWwucHV0KCBwaXBl
bGluZUN1cnNvcl8xLCAiaXNvRGF0ZSIsIG5vd0FzSVNPICk7DQpwaXBlbGluZUN1cnNvcl8xLmRl
c3Ryb3koKTs=</value>
</Values>
