<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">mapDateToIsoDateTime</value>
  <value name="encodeutf8">true</value>
  <value name="body">T2JqZWN0CWRhdGUgPSBudWxsOw0KDQovLyBwaXBlbGluZQ0KSURhdGFDdXJzb3IgcGlwZWxpbmVD
dXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNCmJvb2xlYW4gZXhpc3RzPXBpcGVsaW5lQ3Vy
c29yLmZpcnN0KCJkYXRlIik7DQppZiAoZXhpc3RzKSBkYXRlID0gcGlwZWxpbmVDdXJzb3IuZ2V0
VmFsdWUoKTsNCnBpcGVsaW5lQ3Vyc29yLmRlc3Ryb3koKTsNCg0KaWYgKCFleGlzdHMpIHJldHVy
bjsNCg0KU3RyaW5nIG5vd0FzSVNPID0gbnVsbDsNCmlmKG51bGwgIT0gZGF0ZSl7DQpqYXZhLnV0
aWwuVGltZVpvbmUgdHogPSBqYXZhLnV0aWwuVGltZVpvbmUuZ2V0VGltZVpvbmUoIlVUQyIpOw0K
amF2YS50ZXh0LkRhdGVGb3JtYXQgZGYgPSBuZXcgamF2YS50ZXh0LlNpbXBsZURhdGVGb3JtYXQo
Inl5eXktTU0tZGQnVCdISDptbTpzcy5TU1MnWiciKTsgLy8gUXVvdGVkICJaIiB0byBpbmRpY2F0
ZSBVVEMsIG5vIHRpbWV6b25lIG9mZnNldA0KZGYuc2V0VGltZVpvbmUodHopOw0Kbm93QXNJU08g
PSBkZi5mb3JtYXQoKGphdmEudXRpbC5EYXRlKWRhdGUpOw0KfQ0KDQovLyBwaXBlbGluZQ0KSURh
dGFDdXJzb3IgcGlwZWxpbmVDdXJzb3JfMSA9IHBpcGVsaW5lLmdldEN1cnNvcigpOw0KSURhdGFV
dGlsLnB1dCggcGlwZWxpbmVDdXJzb3JfMSwgImlzb0RhdGUiLCBub3dBc0lTTyApOw0KcGlwZWxp
bmVDdXJzb3JfMS5kZXN0cm95KCk7</value>
</Values>
